version: "3"

services:
  webserver-backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - webserver-backend-db
  webserver-backend-db:
    image: mongo:latest
    ports:
      - 27017:27017
